# Generated by Django 5.0.6 on 2024-05-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
            ],
        ),
    ]
